FORMAT: 1A
HOST: https://v1-asset.api.dudesolutions.io

USECOMMONSDKLIBRARY: TRUE
GENERATEASYNCCODE: TRUE
GENERATEINTERFACES: TRUE
USEMETHODPREFIX: TRUE
USEMODELPOSTFIX: FALSE
USECONTROLLERPOSTFIX: FALSE
USEENUMPOSTFIX: FALSE
USECONSTRUCTORSFORCONFIG: TRUE
CSHARPDEFAULTNAMESPACE: DSI.SDK.Asset
JAVADEFAULTNAMESPACE: io.dudesolutions.asset
BRANDLABEL: Dude Solutions, Inc.
USERAGENT: Dude SDK
NULLIFY404: TRUE
VALIDATEREQUIREDPARAMETERS: FALSE
COLLECTPARAMETERS: TRUE
ARRAYSERIALIZATION: Plain

# Dude Asset Api

## Reference
Good reference document: https://raw.githubusercontent.com/apiaryio/api-blueprint/master/examples/Polls%20API.md

## Authentication
*Dude File Api* uses OAuth v2 Authentication. First you create a new (or acquire existing) OAuth v2 token using [DudeAuth](https://www.dudeauth.com/).

New to *OAuth*?  Check out the [OAuth Bible](http://oauthbible.com/) for good reference material.

## Media Types
Where applicable this API uses the *JSON* media-type to represent resources.
Requests and responses with a message-body use plain JSON to set or update resources.

## Error States
Common [HTTP Response Status Codes](https://github.com/for-GET/know-your-http-well/blob/master/status-codes.md) are used throughout this API.
In addition to standard response codes the response object returned from the server during an exception event may contain additional information in the following JSON format:
{
 "message": "SOME MESSAGE",
 "dudeReferenceId": "3523845A-4729-4CCB-9E16-01DEADF6C2DF",
 "stackTrace": "Null, Typically"
 }

## Data Restriction
Depending on the access level granted to the calling client certain data elements throughout this API will be removed and not returned.

## Dates & Times
All dates and times are represented in [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601) format. In addition, *Dude Security Api* will always provide [Coordinated Universal Time](https://en.wikipedia.org/wiki/Coordinated_Universal_Time).
The API is capable of parsing most date and time formats, however we do require UTC dates and times be provided from all calling systems. We highly recommend you utilize the ISO-8601 standard when communicating dates and time to the API as well.

## Known Issues
None at this time

## Documentation Notes
In Progress

# Group System Information
Check API System Information

## S.I. Check [/]
Retrieve api version, vitals, links, etc.

### GET

+ Response 200 (application/json)
    + Attributes (System Information)

# Group Heartbeat
Check health of dependent services

## Heartbeat Check [/heartbeat]
The heartbeat is exposed and provided to check for availability of the service.
Any response that does not provide a ```200 OK``` response code should be treated as an error.

### GET

+ Response 200 (application/json)
    + Headers

            X-Dude-Api-Limit: Unlimited or Number
            X-Dude-Api-Remaining: Unlimited or Number
            X-Dude-Api-Server: Api Server ID
    + Attributes (Heartbeat)

# Group Import
The assets endpoints allows for the access and management of asset import resources.

## Asset Import Collection [/accounts/{accountId}/import/assets{?page,pagesize,orderby,includeAudit}]
This endpoint allows for the bulk retrieval of asset import jobs

+ Parameters
    + accountId: 2 (number, required) - {INT} The account ID the resource belongs to.
    + page: 1 (number, optional) - {INT} The page to request from the collection.
    + pagesize: 1000 (number, optional) - {INT} The number of records to load in a page from the collection.
    + orderby: AncestorIdPath asc (string, optional) - A string describing the ordering to perform on the collection.
    + includeAudit: true (boolean, optional) - Flag to return audit information from the api

### GET
+ Response 200 (application/json)
    + Attributes (Base Collection Response)
        + `data` (array[Asset Import], required)

## Asset Import Create [/accounts/{accountId}/import/assets]
This endpoint allows for an import to be created and scheduled

+ Parameters
    + accountId: 2 (number, required) - {INT} The account ID the resource belongs to.
    + file: data (file, required) - {FILE} File to upload.

### POST
+ Request (multipart/form-data)

+ Response 201 (application/json)
    + Attributes (Asset Import)

## Asset Import Detail [/accounts/{accountId}/import/assets/{id}]
This endpoint allows asset import data to be found.

+ Parameters
    + accountId: 2 (number, required) - {INT} The account ID the resource belongs to.
    + id: 1 (number, required) - {INT} The import ID for the desired resource.

### GET
+ Response 200 (application/json; charset=utf-8)
    + Attributes (Asset Import)

### PUT

+ Request
    + Attributes (Asset Import)

+ Response 200 (application/json)
    + Attributes (Asset Import)

## Asset Import Log Collection [/accounts/{accountId}/import/assets/{assetImportId}/logs{?page,pagesize,orderby,logType,createdDateTime,rowNumber, sheetNumber}]
    Allows for adding a log entry for an asset import job

+ Parameters
    + accountId: 2 (number, required) - {INT} The account ID the resource belongs to.
    + assetImportId: 1 (number, required) - {INT} The import ID for the desired resource.
    + page: 1 (number, optional) - {INT} The page to request from the collection.
    + pagesize: 1000 (number, optional) - {INT} The number of records to load in a page from the collection.
    + orderby: AncestorIdPath asc (string, optional) - A string describing the ordering to perform on the collection.
    + logType: (enum[string], optional) - {ARRAY} The type of logs that you would like to retrieve
        + Members
            + Info (string)
            + Validation (string)
    + createdDateTime: `2016-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Retrieves all of the logs after the date/time specified
    + rowNumber: 2 (number, optional) - {INT} The row number of the logs to request from the collection.
    + sheetNumber: 2 (number, optional) - {INT} The sheet number of the logs to request from the collection.

### GET
+ Response 200 (application/json)
    + Attributes (Base Collection Response)
        + `data` (array[Import Log], required)

## Asset Import Log Create [/accounts/{accountId}/import/assets/{assetImportId}/logs]
Allows for adding a log entry for an asset import job

+ Parameters
    + accountId: 2 (number, required) - {INT} The account ID the resource belongs to.
    + assetImportId: 1 (number, required) - {INT} The import ID for the desired resource.

### POST
+ Request (application/json)
    + Attributes (Import Log Create)

+ Response 201 (application/json)
    + Attributes (Import Log)

# Group Export
The set of endpoints that allow for exporting assets

## Asset Export [/accounts/{accountId}/export/assets{?includeAssets}]
This endpoint allows for new Asset template data to be created.

+ Parameters
    + accountId: 2 (number, required) - {INT} The account ID for the upload to be associated with.
    + includeAssets: true (boolean, optional) - Indicates that existing assets should be included in the export of the template

### GET
+ Response 200 (application/octet-stream)

# Data Structures

## System Information (object)
Represents the System Information response.

### Properties
+ `application`: `Dude Asset Api` (string, required) - The name of the application.
+ `version` : `1.0.0.0` (string, required) - The assembly version.
+ `apiVersion` : `1.0.0.0` (string, required) - The API version.
+ `vitals` (Heartbeat, required) - The state of the system dependencies.
+ `links` (array[System Links], required) - The API routes.

## System Links (object)
Represents the API routes.

### Properties
+ `endpoint` : `AssetImport` (string, required) - The name of the endpoint.
+ `action` : `Get` (string, required) - The REST action.
+ `route` : `/accounts/{accountId}/import/assets/{id}{?includeAudit}` (string, required) - The route to the endpoint.

## Heartbeat (object)
Represents a heartbeat response.

### Properties
+ `cachevitalcheck`: true (boolean, required) - Vital check to ensure Cache provider is online.
+ `filestoragevitalcheck`: true (boolean, required) - Vital check to ensure file storage provider is online.
+ `filedbvitalcheck`: true (boolean, required) - Vital check to ensure database provider is online.
+ `symantecantivirusprovidervitalcheck`: true (boolean, required) - Vital check to ensure malware provider is online.

## Base Collection Response (object)
Represents a paged response when bulk retrieving from a collection

### Properties
+ `page`: 1 (number, required) - {INT} The current page provided in the response data.
+ `pageSize`: 1000 (number, required) - {INT} The page size returned in the response data.
+ `dataSize`: 1000 (number, required) - {INT} The total records returned in the response.
+ `total`: 2000 (number, required) - {INT} The total number of records available in the collection.

## Audit (object)
Represents the audit fields

### Properties
+ `createdDateTime`: `2015-01-01T00:00:00.123Z` (string, optional) - {DATETIME} The date and time in ISO-8601 format the record was created.
+ `createdByUserId`: 1 (number, optional) - {INT} Information about the user who created the record.
+ `createdByApiClientId`: 1 (number, optional) - {INT} Information about the client who created the record.
+ `updatedDateTime`: `2015-01-01T00:00:00.123Z` (string, optional) - {DATETIME} The date and time in ISO-8601 format the record was last updated.
+ `updatedByUserId`: 1 (number, optional) - {INT} Information about the user who last modified the record.
+ `updatedByApiClientId`: 1 (number, optional) - {INT} Information about the client who last modified the record.

## Asset Import (object)
Represents a asset import resource with base properties.

### Properties
+ `id`: 1 (number, required) - {INT} The ID of the import resource.
+ `fileId`: 2 (number, required) - {INT} The ID of the file resource.
+ `status`: Uploaded (Import Status, required) - The state or status of the asset import resource.
+ `total`: 100 (number, required) - {INT} The total number of assets in the import file
+ `totalSuccessful`: 71 (number, required) - {INT} The total number of assets processed during asset import.
+ `totalErrors`: 10 (number, required) - {INT} The total number of assets processed by the asset import.
+ `totalSkipped`: 19 (number, required) - {INT} The total number of assets processed by the asset import.
+ `validationLogCount`: 10 (number, required) - {INT} The total number of validation logs processed during the asset import.
+ `audit` (Audit, optional) - The audit fields

## Import Status (enum)
+ Uploaded (string)
+ Queued (string)
+ Processing (string)
+ Importing (string)
+ Completed (string)
+ Failed (string)

## Import Log Create (object)
Model to create an import entry

### Properties
+ `logType`: Info (Log Type, required) - The type of the log
+ `message`: Invalid Asset Type (string, required) - The log message
+ `createdDateTime`: `2016-03-04T00:00:00.123Z` (string, required) - {DATETIME} The created date time of the log
+ `sheetName`: Assets (string, optional) - The sheet name associated with the log
+ `rowNumber`: 2 (number, optional) - {INT} The row number associated with the log
+ `dudeReferenceId`: `1332523-2385-92385205` (string, optional) - The Dude Reference Id associated with the log

## Import Log (Import Log Create)
Represents an import log entry

### Properties
+ `id`: 1 (number, required) - {LONG} The ID of the log

## Log Type (enum)
+ Info (string)
+ Validation (string)
